application: onlystatusupdates
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /jquery
  static_dir: jquery
- url: /images
  static_dir: images
- url: /javascripts
  static_dir: javascripts
- url: /stylesheets
  static_dir: stylesheets
- url: /content
  static_dir: content
- url: /.*
  script: main.application
