application: onlystatusupdates
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /images
  static_dir: images
- url: /javascripts
  static_dir: javascripts
- url: /stylesheets
  static_dir: stylesheets
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
  secure: optional
- url: /.*
  script: main.application
  secure: always
